import fs from "fs";



const template = (title) => `

<!DOCTYPE html>

<html lang="en">

<head>

  <meta charset="UTF-8">

  <title>${title} · SideGuy Solutions</title>

</head>

<body>

  <h1>${title}</h1>

  <p>Auto-generated by SideGuy CMS GPT.</p>

</body>

</html>

`;



const pages = [

  "San Diego HVAC Repair",

  "Encinitas Payment Processing",

  "Carlsbad AI Automation",

  "North County Instant Settlements",

  "Solar Installer Payments San Diego",

  "Restaurant Payment Savings San Diego"

  // add unlimited titles here

];



pages.forEach((title) => {

  const filename = title.toLowerCase().replace(/ /g, "-") + ".html";

  fs.writeFileSync(filename, template(title));

  console.log("Generated:", filename);

});