const fs = require('fs');

const path = require('path');



// 100 simple problem titles to turn into pages

const titles = [

  'San Diego Faucet Leak Repair',

  'San Diego Garbage Disposal Stuck',

  'San Diego Dishwasher Not Draining',

  'San Diego Oven Not Heating Up',

  'San Diego Stove Igniter Not Working',

  'San Diego Refrigerator Too Warm',

  'San Diego Freezer Frost Buildup',

  'San Diego Washing Machine Won\'t Spin',

  'San Diego Dryer Not Drying Clothes',

  'San Diego Water Heater Pilot Out',

  'San Diego Low Water Pressure Fix',

  'San Diego Electrical Outlet Not Working',

  'San Diego Light Switch Not Working',

  'San Diego Flickering Lights Problem',

  'San Diego Ceiling Fan Wobbling',

  'San Diego Thermostat Not Responding',

  'San Diego AC Not Blowing Cold Air',

  'San Diego Heater Not Turning On',

  'San Diego Mini Split Not Cooling',

  'San Diego Smart Thermostat Install',

  'San Diego WiFi Keeps Dropping',

  'San Diego Slow Internet Help',

  'San Diego Home Network Setup',

  'San Diego TV Mounting Near Me',

  'San Diego Home Theater Setup Help',

  'San Diego Smart Home Device Setup',

  'San Diego Security Camera Installation',

  'San Diego Doorbell Camera Install',

  'San Diego Garage Door Won\'t Close',

  'San Diego Garage Door Opener Install',

  'San Diego Window Won\'t Close Right',

  'San Diego Sliding Door Off Track',

  'San Diego Screen Door Replacement',

  'San Diego Door Lock Not Working',

  'San Diego Rekey House Locks',

  'San Diego Lost House Keys Help',

  'San Diego Car Keys Locked Inside',

  'San Diego Car Battery Jump Start',

  'San Diego Flat Tire Help',

  'San Diego Mobile Mechanic Near Me',

  'San Diego Oil Change At Home',

  'San Diego Mobile Detail Service',

  'San Diego Pet Stain Carpet Cleaning',

  'San Diego Area Rug Cleaning Pickup',

  'San Diego Sofa Deep Cleaning',

  'San Diego Mattress Deep Cleaning',

  'San Diego Tile And Grout Cleaning',

  'San Diego Shower Glass Hard Water Removal',

  'San Diego Kitchen Deep Cleaning',

  'San Diego Restaurant Hood Cleaning',

  'San Diego Short Term Rental Turnover',

  'San Diego Moving Help By The Hour',

  'San Diego Furniture Assembly Service',

  'San Diego TV And Media Wall Build',

  'San Diego Custom Closet Build Out',

  'San Diego Garage Storage System',

  'San Diego Epoxy Garage Floor',

  'San Diego Backyard Drainage Problems',

  'San Diego Yard Flooding After Rain',

  'San Diego French Drain Installation',

  'San Diego Sump Pump Install',

  'San Diego Retaining Wall Repair',

  'San Diego Concrete Crack Repair',

  'San Diego Driveway Resurfacing',

  'San Diego Paver Patio Repair',

  'San Diego Sprinkler System Not Working',

  'San Diego Broken Sprinkler Head',

  'San Diego Drip Irrigation Install',

  'San Diego Brown Lawn Recovery',

  'San Diego Low Water Landscape Ideas',

  'San Diego Artificial Turf Install',

  'San Diego Tree Trimming Service',

  'San Diego Palm Tree Trimming',

  'San Diego Emergency Tree Removal',

  'San Diego Gutter Cleaning Service',

  'San Diego Roof Leak After Storm',

  'San Diego Attic Insulation Upgrade',

  'San Diego Drafty Window Fix',

  'San Diego Mold Smell In House',

  'San Diego Bathroom Vent Fan Install',

  'San Diego Shower Remodel Estimate',

  'San Diego Kitchen Remodel Estimate',

  'San Diego New Flooring Estimate',

  'San Diego Whole House Paint Estimate',

  'San Diego Interior Designer Consult',

  'San Diego Home Office Setup Help',

  'San Diego Gaming PC Setup Help',

  'San Diego Crypto Wallet Setup Help',

  'San Diego Small Business Website Help',

  'San Diego Google Business Profile Fix',

  'San Diego Online Reviews Help',

  'San Diego Booking System Setup',

  'San Diego Payment Processing Fix',

  'San Diego Instant Settlement Payments',

  'San Diego Contractor Payments Help',

  'San Diego Mobile Invoice Setup',

  'San Diego HVAC Payments Help',

  'San Diego Plumber Payments Help',

  'San Diego Electrician Payments Help',

  'San Diego Landscaper Payments Help',

  'San Diego Cleaning Service Payments',

  'San Diego Handyman Payments Help',

  'San Diego Solana Payments Near Me',

  'San Diego Crypto Payments For Business',

  'San Diego SideGuy Solutions Help'

];



function slugify(title) {

  return title

    .toLowerCase()

    .replace(/[^a-z0-9]+/g, '-')

    .replace(/^-+|-+$/g, '');

}



function buildPage(title) {

  const slug = slugify(title);

  const filename = slug + '.html';

  const filePath = path.join(process.cwd(), filename);



  const html = `<!DOCTYPE html>

<html lang="en">

<head>

  <meta charset="UTF-8" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>${title} · SideGuy Solutions</title>

  <meta name="description" content="${title} — SideGuy Solutions problem-solver landing page generated by the simple builder.">

</head>

<body>

  <main>

    <h1>${title}</h1>

    <p>This page was generated automatically by the SideGuy simple builder script.</p>

    <p>When you\'re ready, you can upgrade this page with your premium template.</p>

    <p><a href="https://sideguysolutions.com/">← Back to SideGuySolutions.com</a></p>

  </main>

</body>

</html>`;



  fs.writeFileSync(filePath, html, 'utf8');

  console.log('Generated:', filename);

}



// Generate all pages

for (const title of titles) {

  buildPage(title);

}



console.log('\\n✅ Done. 100 simple pages generated.');

