#!/usr/bin/env bash
# Quick Swarm Examples

echo "🐝 SideGuy Swarm v8.1 - Quick Start"
echo ""
echo "1. DRY RUN (Safe Preview)"
echo "   DRY_RUN=1 ./swarm-v8.sh"
echo ""
echo "2. LIVE RUN (Manual Review)"
echo "   ./swarm-v8.sh"
echo "   # Then review changes and commit manually"
echo ""
echo "3. AUTO-COMMIT MODE"
echo "   AUTO_COMMIT=1 ./swarm-v8.sh"
echo "   # ⚠️ Use with caution!"
echo ""
echo "4. Custom Thresholds"
echo "   # Edit swarm-v8.sh and adjust:"
echo "   # SCORE_EXPAND=15.0 (default)"
echo "   # SCORE_REWRITE=8.0 (default)"
echo ""
echo "5. View Latest Report"
echo "   ls -lt docs/swarm/*.md | head -1"
echo "   # Or: cat \$(ls -t docs/swarm/*.md | head -1)"
echo ""
echo "6. Revert Last Run"
echo "   DATE=2026-03-24-215549  # Get from report"
echo "   find . -name \"*.bak.\$DATE\" -exec bash -c 'mv \"\$0\" \"\${0%.bak.\$DATE}\"' {} \;"
echo ""
echo "📚 Full docs: docs/swarm/README.md"
