#!/usr/bin/env bash
# Quick reference for Swarm v9 Unified

echo "🧠 SideGuy Swarm v9 Unified - Quick Reference"
echo ""
echo "═══════════════════════════════════════════════"
echo " MODES"
echo "═══════════════════════════════════════════════"
echo ""
echo "1. DRY RUN (Safe Preview)"
echo "   DRY_RUN=1 ./swarm-v9-unified.sh"
echo ""
echo "2. LIVE (Manual Review)"
echo "   ./swarm-v9-unified.sh"
echo "   # Review, then: git add . && git commit"
echo ""
echo "3. AUTO-COMMIT (Use Sparingly)"
echo "   AUTO_COMMIT=1 ./swarm-v9-unified.sh"
echo ""
echo "═══════════════════════════════════════════════"
echo " WHAT IT DOES"
echo "═══════════════════════════════════════════════"
echo ""
echo "✅ Page Upgrades (max 25)"
echo "   - Adds 'Need a clear next step?' section"
echo "   - Adds 'Cost & timing' block (money intent)"
echo "   - Adds 'Text PJ' contact orb"
echo ""
echo "✅ Child Pages (max 15)"
echo "   - {query}-cost.html"
echo "   - {query}-near-me.html"
echo "   - {query}-worth-it.html"
echo ""
echo "✅ Internal Links"
echo "   - Cross-links all new children"
echo ""
echo "✅ Sitemap Updates (max 30)"
echo "   - Auto-appends new pages"
echo ""
echo "✅ Index Updates (max 30)"
echo "   - Adds 'Fresh Help Paths' section"
echo ""
echo "═══════════════════════════════════════════════"
echo " SAFETY"
echo "═══════════════════════════════════════════════"
echo ""
echo "✅ Dry-run mode (no changes)"
echo "✅ Auto-backups (.bak.timestamp)"
echo "✅ No auto-commit by default"
echo "✅ Full report with revert instructions"
echo ""
echo "═══════════════════════════════════════════════"
echo " FILES"
echo "═══════════════════════════════════════════════"
echo ""
echo "INPUT:"
echo "  data/gsc.csv - Google Search Console export"
echo "                 Format: PAGE,QUERY,CLICKS,IMPRESSIONS,CTR,POSITION"
echo ""
echo "OUTPUT:"
echo "  docs/swarm/swarm-v9-report-{timestamp}.md - Detailed report"
echo "  docs/swarm-logs/swarm-v9-{timestamp}.md - Legacy log"
echo "  seo-reserve/swarm-queue.csv - Queue tracking"
echo ""
echo "═══════════════════════════════════════════════"
echo " CONFIGURATION"
echo "═══════════════════════════════════════════════"
echo ""
echo "Edit swarm-v9-unified.sh:"
echo ""
echo "MAX_UPGRADES=25      # In-place HTML upgrades"
echo "MAX_CHILDREN=15      # New child pages"
echo "MAX_SITEMAP=30       # Sitemap additions"
echo "MAX_INDEX=30         # Index additions"
echo ""
echo "SCORE_HIGH=15.0      # High priority threshold"
echo "SCORE_MEDIUM=8.0     # Medium priority threshold"
echo "SCORE_LOW=5.0        # Low priority threshold"
echo ""
echo "MIN_IMPRESSIONS=5    # Minimum to consider"
echo "MIN_POSITION=4       # Best position to target"
echo "MAX_POSITION=30      # Worst position to target"
echo ""
echo "═══════════════════════════════════════════════"
echo " TROUBLESHOOTING"
echo "═══════════════════════════════════════════════"
echo ""
echo "No signals processed?"
echo "  → Check GSC CSV format (header required)"
echo "  → Verify queries meet gold zone (impressions≥5, pos 4-30)"
echo "  → Try without GSC (fallback to inventory scan)"
echo ""
echo "Script hangs?"
echo "  → Check CSV for embedded commas"
echo "  → Use timeout: 'timeout 60 ./swarm-v9-unified.sh'"
echo ""
echo "Want to revert?"
echo "  → Check report for exact revert commands"
echo "  → Backups: *.bak.{timestamp}"
echo ""
echo "═══════════════════════════════════════════════"
echo " DAILY WORKFLOW"
echo "═══════════════════════════════════════════════"
echo ""
echo "1. Export fresh GSC data (weekly)"
echo "2. Dry-run: DRY_RUN=1 ./swarm-v9-unified.sh"
echo "3. Review report in docs/swarm/"
echo "4. If good, run live: ./swarm-v9-unified.sh"
echo "5. Add content to placeholder child pages"
echo "6. Test locally"
echo "7. Commit: git add . && git commit -m 'swarm v9'"
echo ""
echo "═══════════════════════════════════════════════"
echo ""
echo "📚 Full docs: docs/swarm/README-v9-unified.md"
echo ""
