import os
import re
import html as htmlmod
import datetime

LEADERBOARD = "docs/traffic-engine/problem-leaderboard.md"
DISCOVERY_PAGE = "public/discovery/problem-discovery.html"


def slugify(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"\s+", "-", text)
    return re.sub(r"-+", "-", text).strip("-")


def load_problems():
    problems = []
    if not os.path.exists(LEADERBOARD):
        print(f"[skip] Leaderboard not found: {LEADERBOARD}")
        return problems
    with open(LEADERBOARD, encoding="utf-8") as f:
        for line in f:
            if "|" not in line or "---" in line or "Rank" in line:
                continue
            parts = [x.strip() for x in line.split("|")]
            if len(parts) < 4:
                continue
            try:
                rank = int(parts[1])
                topic = parts[2]
                score = int(parts[3])
            except (ValueError, IndexError):
                continue
            if topic:
                problems.append((rank, topic, score))
    return problems


def build_page(problems):
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%B %d, %Y")

    items = ""
    for rank, topic, score in problems[:50]:
        slug = slugify(topic)
        esc = htmlmod.escape(topic)
        items += f'<li><a href="/auto/problem-pages/{slug}.html">{esc}</a> <span class="score">score {score}</span></li>\n'

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>SideGuy Problem Discovery</title>
  <meta name="description" content="The real problems SideGuy is seeing across business, payments, AI, and local services.">
  <style>
    :root{{--mint:#21d3a1;--ink:#073044;--bg:#eefcff}}
    body{{font-family:-apple-system,system-ui,sans-serif;max-width:900px;margin:0 auto;padding:40px 20px;line-height:1.6;background:radial-gradient(ellipse at 20% 40%,#b8f4f0 0%,#d6f5ff 35%,#eefcff 70%,#fff8f0 100%);color:var(--ink)}}
    h1{{font-weight:900;margin-bottom:4px}}
    .meta{{font-size:.85rem;opacity:.7;margin-bottom:28px}}
    .card{{background:#fff;border-radius:16px;padding:20px 24px;margin:20px 0;box-shadow:0 4px 20px rgba(7,48,68,.08)}}
    ul{{padding-left:20px}}
    li{{margin:6px 0}}
    a{{color:#0b5cad;text-decoration:none}}
    a:hover{{text-decoration:underline}}
    .score{{font-size:.8rem;opacity:.6;margin-left:4px}}
    .orb{{position:fixed;right:18px;bottom:18px;background:var(--mint);color:#fff;padding:14px 18px;border-radius:999px;text-decoration:none;font-weight:700;box-shadow:0 6px 20px rgba(33,211,161,.4);animation:pulse 2.5s ease-in-out infinite}}
    @keyframes pulse{{0%,100%{{box-shadow:0 6px 20px rgba(33,211,161,.4)}}50%{{box-shadow:0 6px 32px rgba(33,211,161,.7)}}}}
  </style>
</head>
<body>
  <p><a href="/">← Back to Home</a></p>
  <h1>SideGuy Problem Discovery</h1>
  <p class="meta">Updated {now} · {len(problems)} problems scored</p>

  <div class="card">
    <p>SideGuy tracks real-world problems operators are searching for. These topics are generated by the SideGuy Problem Radar and scored by urgency, money signals, and local intent.</p>
  </div>

  <div class="card">
    <h2>Top Problems</h2>
    <ul>
      {items}
    </ul>
  </div>

  <div class="card">
    <p><strong>SideGuy Mission:</strong> Google discovers the problem. AI explains it. A real human resolves it.</p>
    <p>Text PJ if you need help.</p>
  </div>

  <a class="orb" href="sms:+17735441231">Text PJ</a>
</body>
</html>
"""
    os.makedirs(os.path.dirname(DISCOVERY_PAGE), exist_ok=True)
    with open(DISCOVERY_PAGE, "w", encoding="utf-8") as f:
        f.write(page)
    print(f"Authority discovery page generated: {DISCOVERY_PAGE}")
    print(f"Problems loaded: {len(problems)}")


def run():
    problems = load_problems()
    build_page(problems)


run()
