#!/usr/bin/env bash

echo ""
echo "========================================"
echo "SIDEGUY REAL TEXTING NEXT STEPS"
echo "========================================"
echo ""
echo "1. Copy env template:"
echo "   cp .env.sms.example .env"
echo ""
echo "2. Fill in Twilio credentials and numbers."
echo ""
echo "3. Run app:"
echo "   bash tools/twilio/run-sideguy-sms.sh"
echo ""
echo "4. Expose localhost:8080 with your tunnel of choice."
echo ""
echo "5. In Twilio, set the incoming message webhook to:"
echo "   https://YOUR-PUBLIC-URL/sms/incoming"
echo ""
echo "6. Text your Twilio number and confirm:"
echo "   - auto reply works"
echo "   - escalations log to logs/twilio/escalations.log"
echo "   - PJ alert forwarding works"
echo ""
