#!/usr/bin/env python3
"""
SIDEGUY FUTURE AUTO BUILDER
Automatically builds pages from Future Radar topics.
Reads future/top-topics.txt and generates future-build/<slug>.html
"""

import os, re, json
from datetime import datetime

TOPICS_FILE = "future/top-topics.txt"
OUTPUT_DIR  = "future-build"
PHONE       = "sms:+17735441231"
SITE        = "https://sideguysolutions.com"


def safe(s):
    return (s or "").replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;")


def title_case(slug: str) -> str:
    return " ".join(w.capitalize() for w in slug.replace("-"," ").split())


def build_page(topic_slug: str, topic_title: str) -> str:
    canon = f"{SITE}/future-build/{topic_slug}.html"
    now = datetime.now().strftime("%Y-%m-%d")
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>{safe(topic_title)} | SideGuy Future Guide</title>
  <meta name="description" content="{safe(topic_title)} explained simply. SideGuy publishes early clarity guides before problems become common search queries."/>
  <link rel="canonical" href="{safe(canon)}"/>
  <meta property="og:title" content="{safe(topic_title)}"/>
  <meta property="og:description" content="SideGuy early clarity guide for {safe(topic_title)}."/>
  <meta property="og:type" content="article"/>
  <style>
    :root{{--bg:#06131f;--bg2:#071a2b;--txt:#d7f3ff;--mut:#86b7c7;--line:#12344a;--mint:#50ffc8;}}
    body{{margin:0;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Arial;
      background:radial-gradient(1200px 700px at 20% 10%,#0b2b3d,var(--bg) 55%),linear-gradient(180deg,var(--bg2),var(--bg));
      color:var(--txt);}}
    .wrap{{max-width:760px;margin:0 auto;padding:32px 18px 90px;}}
    h1{{margin:0 0 10px;font-size:28px;line-height:1.2;}}
    h2{{font-size:20px;margin:24px 0 8px;}}
    p{{line-height:1.6;color:rgba(215,243,255,.9);margin:0 0 14px;}}
    ul{{padding-left:20px;}}li{{margin:8px 0;line-height:1.5;color:rgba(215,243,255,.85);}}
    .badge{{display:inline-flex;gap:8px;align-items:center;padding:6px 10px;border-radius:999px;
      border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.04);font-size:13px;color:var(--mut);}}
    .meta{{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:18px;}}
    .cta{{display:inline-flex;align-items:center;gap:10px;padding:12px 14px;border-radius:14px;
      border:1px solid rgba(80,255,200,.30);background:rgba(0,0,0,.22);text-decoration:none;
      color:var(--txt);font-weight:700;margin-top:8px;}}
    .cta:hover{{text-decoration:underline;}}
    .float{{position:fixed;right:18px;bottom:18px;z-index:9999;padding:12px 14px;
      border-radius:999px;border:1px solid rgba(80,255,200,.35);background:rgba(5,25,35,.85);
      display:flex;gap:10px;align-items:center;text-decoration:none;color:var(--txt);
      backdrop-filter:blur(10px);animation:pulse 1.8s infinite ease-in-out;}}
    .dot{{width:12px;height:12px;border-radius:50%;background:var(--mint);
      box-shadow:0 0 18px rgba(80,255,200,.45);}}
    @keyframes pulse{{0%{{transform:translateY(0)}}50%{{transform:translateY(-2px)}}100%{{transform:translateY(0)}}}}.
    footer{{margin-top:32px;color:var(--mut);font-size:13px;}}
  </style>
  <script type="application/ld+json">
  {{
    "@context":"https://schema.org",
    "@type":"Article",
    "headline":"{safe(topic_title)}",
    "description":"SideGuy early clarity guide for {safe(topic_title)}.",
    "url":"{safe(canon)}",
    "publisher":{{"@type":"Organization","name":"SideGuy Solutions","url":"{SITE}/"}}
  }}
  </script>
</head>
<body>
  <div class="wrap">
    <div class="meta">
      <span class="badge">🛰 Future Radar</span>
      <span class="badge">Generated {now}</span>
      <span class="badge"><a href="/future-build/index.html" style="color:var(--mut)">← Future Index</a></span>
    </div>

    <h1>{safe(topic_title)}</h1>

    <p>
      This page was generated by the SideGuy Future Radar system.
      It identifies emerging operator problems and publishes early
      clarity guides before they become common search queries.
    </p>

    <h2>Why this matters</h2>
    <p>
      When technology changes quickly, people search for solutions
      before documentation exists. SideGuy publishes early guides
      so operators can understand the problem fast — and find the
      shortest working path to a fix.
    </p>

    <h2>Typical solution path</h2>
    <ul>
      <li>Understand the underlying system and what state it should be in</li>
      <li>Identify the failure point — config, keys, upstream service, or logic error</li>
      <li>Implement the minimum working fix and verify the result</li>
      <li>Document the fix so the next occurrence takes seconds to resolve</li>
    </ul>

    <h2>Get help now</h2>
    <p>If you're stuck and this is affecting revenue or customer access, don't wait:</p>
    <a class="cta" href="{PHONE}">💬 Text PJ · 773-544-1231</a>

    <footer>
      <strong>SideGuy</strong> — Clarity before cost.
      San Diego · <a href="/" style="color:var(--mut)">sideguysolutions.com</a>
    </footer>
  </div>

  <a class="float" href="{PHONE}">
    <span class="dot"></span>
    <span><strong>Text PJ</strong></span>
  </a>
</body>
</html>
"""


def main():
    if not os.path.exists(TOPICS_FILE):
        print(f"[future-auto-builder] ERROR: {TOPICS_FILE} missing. Run future-radar.sh first.")
        return

    topics = [t.strip() for t in open(TOPICS_FILE).read().splitlines() if t.strip()]
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    built = []
    skipped = 0

    for t in topics[:50]:
        slug = t.replace(" ", "-")
        path = os.path.join(OUTPUT_DIR, f"{slug}.html")
        title = title_case(t)
        # Skip if already exists (idempotent)
        if os.path.exists(path):
            skipped += 1
            continue
        html = build_page(slug, title)
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        built.append((slug, title))
        print(f"  ✓ {path}")

    # Build/update index
    cards = "\n".join(
        f'    <li><a href="{s}.html">{safe(ttl)}</a></li>'
        for s, ttl in (built + [(s, title_case(s)) for s in
            [os.path.basename(p).replace(".html","")
             for p in os.listdir(OUTPUT_DIR) if p.endswith(".html") and p != "index.html"]
            if (s, title_case(s)) not in built])
    )
    index_html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>Future Problem Index | SideGuy</title>
  <meta name="description" content="Auto-generated pages from SideGuy Future Radar — emerging operator problems before they become common queries."/>
  <link rel="canonical" href="{SITE}/future-build/index.html"/>
  <style>
    body{{margin:0;font-family:ui-sans-serif,system-ui,Arial;background:#06131f;color:#d7f3ff;padding:32px 18px 80px;}}
    h1{{font-size:26px;margin:0 0 8px;}}
    p{{color:#86b7c7;margin:0 0 18px;}}
    ul{{padding-left:18px;}}li{{margin:8px 0;}}
    a{{color:#50ffc8;}}
    .float{{position:fixed;right:18px;bottom:18px;padding:12px 14px;border-radius:999px;
      border:1px solid rgba(80,255,200,.35);background:rgba(5,25,35,.85);
      text-decoration:none;color:#d7f3ff;display:flex;gap:10px;align-items:center;
      backdrop-filter:blur(10px);}}
    .dot{{width:12px;height:12px;border-radius:50%;background:#50ffc8;}}
  </style>
</head>
<body>
  <h1>Future Problem Index</h1>
  <p>
    These pages are generated automatically from real-world technology signals
    detected by the SideGuy Future Radar. Updated: {datetime.now().strftime("%Y-%m-%d")}.
  </p>
  <ul>
{cards}
  </ul>
  <a class="float" href="{PHONE}">
    <span class="dot"></span>
    <span><strong>Text PJ</strong></span>
  </a>
</body>
</html>
"""
    with open(os.path.join(OUTPUT_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(index_html)

    print(f"\n[future-auto-builder] Built: {len(built)}  Skipped (existing): {skipped}")
    print(f"[future-auto-builder] Index → {OUTPUT_DIR}/index.html")


if __name__ == "__main__":
    main()
